version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/server/src
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
    links:
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432
networks:
  default:
    external:
      name: auth-module
