version: "3"

services:
  frontend:
    container_name: auth_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/
      - ./node_modules:/usr/src/app/node_modules
