version: "3"

services:
  frontend:
    container_name: auth_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/frontend/src
      - ./node_modules:/frontend/node_modules

    network_mode: host
